# Generated by Django 4.2.10 on 2024-03-17 21:28
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('reporter_last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('reporter_phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('reporter_email', models.CharField(blank=True, max_length=50, null=True)),
                ('reporter_description', models.TextField(blank=True, max_length=400, null=True)),
                ('version', models.IntegerField(default=0)),
                ('complaint_title', models.CharField(max_length=200)),
                ('type_complaint', models.PositiveSmallIntegerField(choices=[(1, 'Noise Complaint'), (2, 'Messiness'), (3, 'Stolen Item'), (4, 'Maintenance'), (5, 'Property Damage'), (6, 'Parking Lot'), (7, 'Loitering'), (8, 'Other')], default=1)),
                ('sent_date', models.DateTimeField(verbose_name='Date Sent')),
                ('incident_date', models.DateTimeField(verbose_name='Date of Incident')),
                ('respondent_name', models.CharField(blank=True, max_length=50, null=True)),
                ('respondent_location', models.TextField(blank=True, max_length=200, null=True)),
                ('location_address', models.CharField(max_length=50)),
                ('location_description', models.TextField(max_length=500)),
                ('incident_description', models.TextField(max_length=500)),
                ('additional_information', models.TextField(blank=True, max_length=500, null=True)),
                ('expected_completion', models.DateTimeField(null=True, verbose_name='Expected time completed')),
                ('complaint_status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'In Progress'), (3, 'Action Taken')], default=1)),
            ],
        ),
    ]
