# Generated by Django 4.2.10 on 2024-03-31 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('whistleblower', '0002_complaint_file1_complaint_file2_complaint_file3'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'In Progress'), (3, 'Resolved')], default=1),
        ),
    ]
