# Generated by Django 4.2.10 on 2024-03-21 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whistleblower', '0002_complaint_file1_complaint_file2_complaint_file3'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['group']},
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50, null=True)),
                ('groups', models.ManyToManyField(null=True, to='whistleblower.buildinggroup')),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.AddField(
            model_name='complaint',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='whistleblower.buildinggroup'),
        ),
    ]
