# Generated by Django 4.2.10 on 2024-04-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whistleblower', '0003_complaint_reporter_alter_complaint_complaint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolution_notes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
