# Generated by Django 4.2.10 on 2024-03-21 22:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('whistleblower', '0003_buildinggroup_alter_complaint_options_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildinggroup',
            options={},
        ),
        migrations.AddField(
            model_name='buildinggroup',
            name='users',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
