# Generated by Django 4.2.10 on 2024-03-22 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whistleblower', '0004_alter_buildinggroup_options_buildinggroup_users_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={},
        ),
    ]
