# Generated by Django 4.2.10 on 2024-04-02 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whistleblower', '0004_complaint_resolution_notes'),
        ('whistleblower', '0005_alter_complaint_options'),
    ]

    operations = [
    ]
