# Generated by Django 4.2.10 on 2024-04-10 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whistleblower', '0006_alter_complaint_complaint_status'),
        ('whistleblower', '0006_merge_20240402_1125'),
    ]

    operations = [
    ]
