# Generated by Django 4.2.10 on 2024-04-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whistleblower', '0007_merge_20240409_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='expected_completion',
        ),
        migrations.AddField(
            model_name='complaint',
            name='urgency',
            field=models.IntegerField(blank=True, null=True, verbose_name='How urgent from 1 to 5?'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='incident_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='sent_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Sent'),
        ),
    ]
