# Generated by Django 4.2.10 on 2024-04-09 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('whistleblower', '0008_remove_complaint_expected_completion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
