# Generated by Django 4.2.10 on 2024-04-16 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whistleblower', '0007_merge_20240410_1854'),
        ('whistleblower', '0009_alter_complaint_reporter'),
    ]

    operations = [
    ]
