# Generated by Django 4.2.10 on 2024-04-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whistleblower', '0010_merge_20240415_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='reporter_description',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='reporter_phone_number',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='version',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='urgency',
            field=models.IntegerField(default=1, verbose_name='How urgent from 1 to 5?'),
        ),
    ]
