# Generated by Django 4.2.10 on 2024-04-26 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whistleblower', '0011_remove_complaint_reporter_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='respondent_location',
        ),
    ]
