# Generated by Django 4.2.10 on 2024-04-27 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whistleblower', '0012_remove_complaint_respondent_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='additional_information',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Additional Information'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_title',
            field=models.CharField(max_length=200, verbose_name='Title*'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='report_files', verbose_name='File 1'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='report_files', verbose_name='File 2'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to='report_files', verbose_name='File 3'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='whistleblower.buildinggroup', verbose_name='Building Group*'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='incident_date',
            field=models.DateTimeField(verbose_name='Date of Incident*'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='incident_description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Incident Description'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='location_address',
            field=models.CharField(max_length=50, verbose_name='Location Address*'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='location_description',
            field=models.TextField(max_length=500, verbose_name='Location Description*'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='respondent_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Respondent Name'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='type_complaint',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Noise Complaint'), (2, 'Messiness'), (3, 'Stolen Item'), (4, 'Maintenance'), (5, 'Property Damage'), (6, 'Parking Lot'), (7, 'Loitering'), (8, 'Other')], default=1, verbose_name='Complaint Type*'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='urgency',
            field=models.IntegerField(default=1, verbose_name='How urgent from 1 to 5?*'),
        ),
    ]
